# Generated by Django 4.1.2 on 2022-11-04 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseriesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='modelVideo',
        ),
    ]
